#!/bin/env ruby

require 'rubygems'
require 'rake'
require 'fileutils'
require 'json' # gem install json --version=1.4.3

# gem install rubyzip --version=0.9.4
gem 'rubyzip'
require 'zip/zip'
require 'zip/zipfilesystem'

class BastardDeployer
  def initialize
    @excludes = [
      '.git',
      '.gitmodules',
      '*.wgz',
      'deploy',
      'wrt_bastard/*.markdown',
      'wrt_bastard/deploy',
      'wrt_bastard/lib/*',
      '.zip',
      'app/*'
    ]

    @deploy_to = 'deploy'
    @deploy_tmp = File.join(@deploy_to, 'tmp')
    @environment = 'production'
  end

  def deploy
    FileUtils.rm_r @deploy_to, :force=>true

    FileUtils.mkdir_p @deploy_to
    FileUtils.mkdir_p @deploy_tmp

    list = FileList['**/*']

    @excludes.each do |exclude|
      list = list.exclude(exclude)
    end

    list.each do |filename|
      #puts filename
      dirname = File.dirname(filename)
      destination_dir = File.join(@deploy_tmp, dirname)
      FileUtils.mkdir_p destination_dir

      #puts dirname
      unless File.directory?(filename)
        FileUtils.cp_r filename, destination_dir
      end
    end

    bundle_assets

    change_environment

    create_wgz

    FileUtils.rm_r @deploy_to, :force=>true
  end

  def bundle_assets
    puts "Bundling assets"
    str = File.read('config/dependencies.js').gsub('var config = ', '')
    assets = JSON.parse(str)

    join_files(assets['javascripts'], '.js')
    join_files(assets['stylesheets'], '.css')
  end

  def join_files(files, extension)
    str = files.inject("") do |memo, file|
      memo << File.read(file['path'] + file['filename'] + extension) << "\n"
    end

    output_dir = case extension
      when '.js'
        File.join(@deploy_tmp, 'app', 'javascripts')
      when '.css'
        File.join(@deploy_tmp, 'app', 'stylesheets')
    end

    FileUtils.mkdir_p output_dir
    file_tmp = File.join(output_dir, "bundle_tmp#{extension}")
    file = File.join(output_dir, "bundle#{extension}")
    File.open(file_tmp, 'w+'){|f| f.puts(str)}
    `java -jar #{File.join("wrt_bastard", "lib", "yuicompressor.jar")} #{file_tmp} > #{file}`
    FileUtils.rm_f file_tmp
  end

  def change_environment
    "Changing environment to #{@environment}"
    File.open(File.join(@deploy_tmp, 'config', 'environment.js'), 'w+') do |f|
      f.puts "var ENV='#{@environment}'"
    end
  end

  def create_wgz
    path = @deploy_tmp
    path.sub!(%r[/$],'')
    archive = File.join(File.basename(Dir.pwd)) + '_release.wgz'
    FileUtils.rm_rf archive

    Zip::ZipFile.open(archive, 'w') do |zipfile|
      Dir["#{path}/**/**"].each do |file|
        entry = "#{File.basename(Dir.pwd)}/" + file.sub(path + '/', "")
        puts "Adding to .wgz: #{entry}"
        zipfile.add(entry, file)
      end
    end
  end
end

b = BastardDeployer.new
b.deploy
